# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255, unique=True)),
                ('codigo', models.CharField(max_length=50)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['nome_produto']},
        ),
        migrations.CreateModel(
            name='RegraFaturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_emit', models.CharField(db_index=True, max_length=20)),
                ('cnpj_dest', models.CharField(db_index=True, max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ordem_de_servico', 'Ordem de serviço'), ('conhecimento_de_transporte', 'Conhecimento de transporte')], default='conhecimento_de_transporte', max_length=40)),
            ],
            options={'ordering': ['cnpj_emit', 'cnpj_dest']},
        ),
        migrations.CreateModel(
            name='RegraPagador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_emit', models.CharField(db_index=True, max_length=20)),
                ('cnpj_dest', models.CharField(db_index=True, max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pagador', models.CharField(help_text='0=remetente, 1=destinatario', max_length=1)),
            ],
            options={'ordering': ['cnpj_emit', 'cnpj_dest']},
        ),
        migrations.CreateModel(
            name='RegraPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_emit', models.CharField(db_index=True, max_length=20)),
                ('cnpj_dest', models.CharField(db_index=True, max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('campo_peso', models.CharField(default='pesoL', max_length=40)),
            ],
            options={'ordering': ['cnpj_emit', 'cnpj_dest']},
        ),
        migrations.CreateModel(
            name='RegraTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_emit', models.CharField(db_index=True, max_length=20)),
                ('cnpj_dest', models.CharField(db_index=True, max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('usiminas', 'Usiminas'), ('terminal', 'Terminal fixo')], max_length=20)),
                ('valor', models.CharField(blank=True, max_length=30)),
            ],
            options={'ordering': ['cnpj_emit', 'cnpj_dest']},
        ),
        migrations.CreateModel(
            name='RegraValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_emit', models.CharField(db_index=True, max_length=20)),
                ('cnpj_dest', models.CharField(db_index=True, max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('campo_valor', models.CharField(default='vLiq', max_length=40)),
            ],
            options={'ordering': ['cnpj_emit', 'cnpj_dest']},
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_emit', models.CharField(db_index=True, max_length=20)),
                ('cnpj_dest', models.CharField(db_index=True, max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.CharField(max_length=200)),
            ],
            options={'ordering': ['cnpj_emit', 'cnpj_dest']},
        ),
        migrations.AddConstraint(
            model_name='regrafaturamento',
            constraint=models.UniqueConstraint(fields=('cnpj_emit', 'cnpj_dest'), name='uq_faturamento_emit_dest'),
        ),
        migrations.AddConstraint(
            model_name='regrapagador',
            constraint=models.UniqueConstraint(fields=('cnpj_emit', 'cnpj_dest'), name='uq_pagador_emit_dest'),
        ),
        migrations.AddConstraint(
            model_name='regrapeso',
            constraint=models.UniqueConstraint(fields=('cnpj_emit', 'cnpj_dest'), name='uq_peso_emit_dest'),
        ),
        migrations.AddConstraint(
            model_name='regraterminal',
            constraint=models.UniqueConstraint(fields=('cnpj_emit', 'cnpj_dest'), name='uq_terminal_emit_dest'),
        ),
        migrations.AddConstraint(
            model_name='regravalor',
            constraint=models.UniqueConstraint(fields=('cnpj_emit', 'cnpj_dest'), name='uq_valor_emit_dest'),
        ),
        migrations.AddConstraint(
            model_name='rota',
            constraint=models.UniqueConstraint(fields=('cnpj_emit', 'cnpj_dest'), name='uq_rota_emit_dest'),
        ),
    ]
